Repository akaihola/darker, pull requests merged in 2020-08, with the labels that each got.

#28 Linenum diffing refactor
  src/darker/__main__.py
  src/darker/diff.py
  src/darker/git.py
  src/darker/tests/test_diff.py
  src/darker/tests/test_git.py
Labels: enhancement

#36 `--check` option, mirroring `black --check`
  CHANGES.rst
  README.rst
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_main.py
  src/darker/version.py
Labels: enhancement

#37 Paths from `--diff` now relative to workdir (#34)
  CHANGES.rst
  src/darker/__main__.py
  src/darker/tests/test_main.py
Labels: bug

#45 Document how to enable darker instead of black in vscode.
  README.rst
Labels: documentation

#48 Reformat newly added files, too
  CHANGES.rst
  src/darker/__main__.py
  src/darker/git.py
  src/darker/tests/test_git.py
Labels: enhancement

#50 `--no-skip-string-normalization` option
  CHANGES.rst
  README.rst
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/tests/conftest.py
  src/darker/tests/test_command_line.py
Labels: enhancement

#46 Optionally print the diff in color.
  CHANGES.rst
  README.rst
  mypy.ini
  pytest.ini
  setup.cfg
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/tests/test_main.py
Labels: enhancement

#43 WIP: Add -r / --revision argument for specifying which Git revision to compare to
  CHANGES.rst
  README.rst
  setup.cfg
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/git.py
  src/darker/tests/conftest.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_revision.py
Labels: enhancement

#33 Add support for linters
  CHANGES.rst
  README.rst
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/git.py
  src/darker/linting.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_git.py
  src/darker/tests/test_linting.py
  src/darker/tests/test_main.py
Labels: enhancement

#54 Bugfix: Linter support to diff against given revision
  src/darker/__main__.py
  src/darker/git.py
  src/darker/linting.py
  src/darker/tests/test_git.py
  src/darker/tests/test_linting.py
Labels: bug

#53 Release 1.1.0
  CHANGES.rst
  README.rst
  src/darker/version.py
Labels: release

#39 Darker source code verifiable with Flake8
  CHANGES.rst
  pytest.ini
  setup.cfg
  src/darker/linting.py
  src/darker/tests/test_diff.py
  src/darker/verification.py
Labels: CI
