Repository akaihola/darker, pull requests merged in 2020-07, with the labels that each got.

#25 Improvements to README and the changelog (issue #22)
  CHANGES.rst
  README.rst
  src/darker/command_line.py
Labels: documentation

#29 Release version 1.0.0
  CHANGES.rst
  src/darker/version.py
Labels: release

#30 Changelog to link to commit logs, not diffs
  CHANGES.rst
Labels: documentation

#32 Don't show traceback if there are no SRCs specified
  src/darker/__main__.py
  src/darker/command_line.py
Labels: enhancement
