Repository akaihola/darker, pull requests merged in 2021-09, with the labels that each got.

#189 Fix gen_python_files usage for black>=21.7b1.dev9
  CHANGES.rst
  src/darker/black_diff.py
Labels: bug

#190 Update black required versions
  setup.cfg
  src/darker/black_diff.py
Labels: bug, CI

#185 Always run Git in English
  src/darker/git.py
  src/darker/tests/test_git.py
Labels: bug

#184 Add new contributors from 2021 Aug & Sep
  CONTRIBUTORS.rst
  README.rst
Labels: documentation

#187 Add a sidebar to README
  README.rst
  setup.py
Labels: documentation

#177 Release 1.3.0
  CHANGES.rst
  README.rst
  src/darker/version.py
Labels: release

#139 Fix assumption of root being CWD in print_diff
  CHANGES.rst
  src/darker/__main__.py
  src/darker/tests/test_main.py
Labels: bug

#192 Shorter and more user friendly import errors
  CHANGES.rst
  src/darker/__main__.py
  src/darker/exceptions.py
  src/darker/help.py
  src/darker/import_sorting.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_main.py
Labels: enhancement

#194 Mention Black's possible upcoming line range formatting support in README
  CHANGES.rst
  README.rst
Labels: documentation

#197 Reformat empty and all-whitespace files properly
  CHANGES.rst
  src/darker/black_diff.py
  src/darker/tests/test_black_diff.py
Labels: enhancement

#199 Allow `pre-commit -o HEAD`
  CHANGES.rst
  src/darker/__main__.py
  src/darker/tests/test_main.py
Labels: enhancement

#191 Add contributors for 1.3.1 release
  CONTRIBUTORS.rst
  README.rst
Labels: documentation
