Repository akaihola/darker, pull requests merged in 2021-06, with the labels that each got.

#149 Upgrade to MyPy 0.910 in the test suite
  CHANGES.rst
  setup.cfg
Labels: CI

#138 Fix AST verification and historical comparisons
  CHANGES.rst
  src/darker/__main__.py
  src/darker/git.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main.py
  src/darker/utils.py
Labels: bug

#136 Add new contributors as of version 1.2.4 to `README.rst`
  README.rst
Labels: documentation

#142 Fix Black formatting on Windows (issue #133)
  CHANGES.rst
  src/darker/black_diff.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_utils.py
  src/darker/utils.py
Labels: bug

#150 Conda instructions
  CHANGES.rst
  README.rst
Labels: documentation

#153 Add skip-magic-trailing-comma option to darker and pass it on to black.
  CHANGES.rst
  CONTRIBUTORS.rst
  README.rst
  src/darker/__main__.py
  src/darker/black_diff.py
  src/darker/command_line.py
  src/darker/help.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_command_line.py
Labels: enhancement
