Repository akaihola/darker, pull requests merged in 2021-04, with the labels that each got.

#117 Keep encoding and newlines intact. Fixes #115.
  src/darker/__main__.py
  src/darker/black_diff.py
  src/darker/import_sorting.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_git.py
  src/darker/tests/test_import_sorting.py
  src/darker/tests/test_main.py
  src/darker/tests/test_utils.py
  src/darker/utils.py
Labels: enhancement

#119 Add contributors to README (2021-04)
  README.rst
Labels: documentation

#123 Read `README.rst` excplicitly as UTF-8 in `setup.py` to fix Windows installation problems
  CHANGES.rst
  setup.py
Labels: bug

#74 Move help texts to a separate module
  CHANGES.rst
  mypy.ini
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/help.py
  src/darker/tests/test_command_line.py
Labels: refactoring

#95 Clean up the `debug_dump()` function
  src/darker/tests/test_utils.py
  src/darker/utils.py
  src/darker/verification.py
Labels: refactoring

#97 Increase test coverage
  src/darker/tests/conftest.py
  src/darker/tests/helpers.py
  src/darker/tests/test_git.py
  src/darker/tests/test_linting.py
  src/darker/tests/test_main.py
Labels: CI

#98 Git call refactoring
  src/darker/git.py
  src/darker/tests/conftest.py
  src/darker/tests/test_git.py
Labels: refactoring

#99 Git repo fixture enhancements
  src/darker/tests/conftest.py
Labels: CI, refactoring

#116 Improve compatibility with `pre-commit`
  CHANGES.rst
  src/darker/git.py
  src/darker/help.py
  src/darker/tests/test_git.py
Labels: bug

#125 newline-unit-test-fix
  src/darker/black_diff.py
  src/darker/diff.py
  src/darker/tests/conftest.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_git.py
  src/darker/tests/test_linting.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_revision.py
  src/darker/tests/test_utils.py
Labels: CI

#120 Run CI on Windows
  .github/workflows/python-package.yml
Labels: CI
