Repository akaihola/darker, pull requests merged in 2021-05, with the labels that each got.

#126 Return 1 also for linting errors
  setup.cfg
  src/darker/__main__.py
  src/darker/linting.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_linting.py
  src/darker/tests/test_main.py
  src/darker/tests/test_utils.py
Labels: bug

#94 Binary search to minimize number of context lines
  CHANGES.rst
  src/darker/__main__.py
  src/darker/tests/test_main.py
  src/darker/tests/test_verification.py
  src/darker/verification.py
Labels: enhancement

#127 Point build badge to the GitHub action, not Travis
  .github/workflows/python-package.yml
  README.rst
Labels: CI

#129 Release version 1.2.3
  CHANGES.rst
  src/darker/version.py
Labels: release

#135 Mypy & Black 21.x compatibility
  mypy.ini
  src/darker/black_diff.py
Labels: CI

#134 Ignore ~/.gitconfig when running git tests
  CHANGES.rst
  src/darker/tests/conftest.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main.py
Labels: CI

#132 Fix crash when `isort` isn't installed
  CHANGES.rst
  mypy.ini
  src/darker/help.py
  src/darker/import_sorting.py
  src/darker/tests/conftest.py
  src/darker/tests/helpers.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_import_sorting.py
  src/darker/tests/test_main.py
Labels: bug

#96 docs: Set autoread for vim integration to get the buffer to automically reload
  README.rst
Labels: documentation
