Repository akaihola/darker, pull requests merged in 2021-07, with the labels that each got.

#158 fix: always give git_get_content_at_revision a relative path
  CHANGES.rst
  src/darker/__main__.py
  src/darker/git.py
Labels: bug

#141 Use pytest-kwparametrize
  src/darker/tests/test_argparse_helpers.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_chooser.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_config.py
  src/darker/tests/test_diff.py
  src/darker/tests/test_git.py
  src/darker/tests/test_import_sorting.py
  src/darker/tests/test_linting.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_revision.py
  src/darker/tests/test_utils.py
  src/darker/tests/test_verification.py
Labels: CI

#84 Make `--diff` output identical to Black
  CHANGES.rst
  src/darker/__main__.py
  src/darker/git.py
  src/darker/import_sorting.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_revision.py
Labels: enhancement, help wanted

#165 Add the `-d` / `--stdout` option. Fixes #164.
  CHANGES.rst
  README.rst
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/config.py
  src/darker/help.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_config.py
  src/darker/tests/test_main.py
Labels: enhancement

#154 Document contributors for the 1.3.0 release
  CONTRIBUTORS.rst
  README.rst
Labels: documentation

#159 Hide expected Git errors from stderr
  CHANGES.rst
  src/darker/git.py
  src/darker/tests/test_git.py
Labels: enhancement
