Repository akaihola/darker, pull requests merged in 2021-10, with the labels that each got.

#207 Mention `yapf` and `yapf_diff` in `README`
  README.rst
Labels: documentation

#217 Release 1.3.1
  CHANGES.rst
  README.rst
  src/darker/version.py
Labels: release

#140 Allow running on plain (non-git) directories
  CHANGES.rst
  src/darker/__main__.py
  src/darker/git.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main.py
Labels: enhancement

#195 Improve Git robustness
  src/darker/__main__.py
  src/darker/git.py
  src/darker/tests/conftest.py
  src/darker/tests/test_git.py
Labels: enhancement

#196 Disable Pylint bad-continuation check
  .pylintrc
Labels: CI

#230 handle FileSkipComment
  CHANGES.rst
  src/darker/import_sorting.py
  src/darker/tests/test_import_sorting.py
Labels: enhancement

#236 Fix the link to `README.rst` on PyPI
  README.rst
Labels: bug, documentation
