Repository akaihola/darker, pull requests merged in 2022-02, with the labels that each got.

#258 Fix tests for Pygments 2.11.2
  CHANGES.rst
  src/darker/tests/test_highlighting.py
Labels: bug

#270 Add compatibility with Black >= 22.1
  .github/workflows/python-package.yml
  CHANGES.rst
  constraints-oldest.txt
  mypy.ini
  setup.cfg
  src/darker/black_compat.py
  src/darker/config.py
  src/darker/import_sorting.py
  src/darker/tests/conftest.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_import_sorting.py
  src/darker/tests/test_main.py
Labels: bug

#257 No additional newline with `--stdout` flag.
  CHANGES.rst
  src/darker/__main__.py
  src/darker/tests/test_main.py
Labels: bug

#280 Release 1.4.0
  CHANGES.rst
  README.rst
  src/darker/version.py
Labels: release

#278 Contributors since November 2021
  CONTRIBUTORS.rst
  README.rst
Labels: documentation

#255 VSCode `.py.tmp` file should be reformatted
  CHANGES.rst
  src/darker/__main__.py
  src/darker/git.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main.py
Labels: bug

#283 Update Mypy to version 0.931
  CHANGES.rst
  constraints-oldest.txt
  setup.cfg
  src/darker/config.py
Labels: CI

#282 Update the GitHub Action to use Darker 1.4.0
  CHANGES.rst
  README.rst
  action.yml
Labels: enhancement

#248 Build with Nix on Ubuntu and macos
  .github/workflows/python-package.yml
  default.nix
Labels: CI

#292 Fix highlighting in a `README` code block
  README.rst
Labels: bug, documentation

#291 Contributors since Feb 2022
  CONTRIBUTORS.rst
  README.rst
Labels: documentation

#288 Re-enable Win and Python 3.6/3.7/3.8/3.9 builds
  .github/workflows/python-package.yml
Labels: bug, CI

#289 Fix `options:` parameter documentation for GitHub Action
  action.yml
Labels: CI

#295 Release 1.4.1
  CHANGES.rst
  README.rst
  action.yml
Labels: release

#299 Document `isort` same-env requirement
  CHANGES.rst
  README.rst
Labels: documentation

#298 Document VSCode / `--lint` incompatibility
  CHANGES.rst
  README.rst
Labels: documentation

#293 Normalize strings in Black formatting of Darker's own code base
  pyproject.toml
Labels: CI

#302 NixOS build failed when `pytest-darker` called `pylint`
  .github/workflows/python-package.yml
  CHANGES.rst
Labels: bug, CI

#296 Include `isort@main` in `test-future` workflow
  .github/workflows/python-package.yml
  .github/workflows/test-future.yml
  CHANGES.rst
  constraints-future.txt
Labels: CI

#305 Fix slow windows test
  CHANGES.rst
  src/darker/tests/test_git.py
Labels: CI

#307 Mention in the `README`: `pytest-darker`, IDEs and `pre-commit`
  README.rst
Labels: documentation

#310 Check Darker code with `bandit`, `codespell`, `pyupgrade` and `safety`
  .github/workflows/python-package.yml
  action/main.py
  constraints-oldest.txt
  setup.cfg
  src/darker/argparse_helpers.py
  src/darker/command_line.py
  src/darker/diff.py
  src/darker/git.py
  src/darker/import_sorting.py
  src/darker/linting.py
  src/darker/tests/conftest.py
  src/darker/tests/test_difflib.py
  src/darker/tests/test_git.py
  src/darker/tests/test_linting.py
  src/darker/utils.py
Labels: question, CI

#303 Skip linting in certain CI configurations
  .github/workflows/python-package.yml
  pytest.ini
Labels: CI

#290 Automate contributor list generation
  .gitignore
  CONTRIBUTORS.rst
  README.rst
  constraints-oldest.txt
  contributors.yaml
  mypy.ini
  release_tools/__init__.py
  release_tools/update_contributors.py
  setup.cfg
Labels: documentation

#314 Run Bandit checks in a dedicated Workflow
  .bandit.code.yaml
  .bandit.tests.yaml
  .github/workflows/bandit.yml
  .github/workflows/python-package.yml
  contributors.yaml
Labels: CI
