Repository akaihola/darker, pull requests merged in 2022-03, with the labels that each got.

#331 Upgrade to `mypy==0.940`
  constraints-oldest.txt
  release_tools/update_contributors.py
  setup.cfg
Labels: CI

#330 Replace vote link in `README` with link to community support channel
  README.rst
Labels: documentation

#329 Version bump tool
  .github/workflows/python-package.yml
  .github/workflows/test-bump-version.yml
  CHANGES.rst
  pyproject.toml
  release_tools/bump_version.py
Labels: CI

#333 Add contributors since March 2022
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
  release_tools/update_contributors.py
Labels: documentation

#332 Release 1.4.2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/test-bump-version.yml
  CHANGES.rst
  README.rst
  action.yml
  release_tools/bump_version.py
  src/darker/version.py
Labels: release

#179 --jobs argument
  CHANGES.rst
  README.rst
  mypy.ini
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/concurrency.py
  src/darker/config.py
  src/darker/help.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_concurrency.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_blacken_single_file.py
  src/darker/tests/test_main_revision.py
Labels: enhancement

#340 Avoid memory leak from using `@lru_cache` on a method
  CHANGES.rst
  src/darker/git.py
Labels: bug

#344 Fix bandit reporting in GitHub Workflows by using my own branch of the action
  .github/workflows/bandit.yml
Labels: CI

#339 Upgrade GitHub Action checkout
  .github/workflows/bandit.yml
  .github/workflows/python-package.yml
  .github/workflows/test-bump-version.yml
  .github/workflows/test-future.yml
Labels: CI

#313 GitHub Action options to invoke linters through Darker
  .bandit.code.yaml
  .github/workflows/bandit.yml
  .github/workflows/yaml-lint.yml
  CHANGES.rst
  README.rst
  action.yml
  action/main.py
  action/tests/test_main.py
  mypy.ini
  pyproject.toml
Labels: CI

#338 Build and validate source and wheel distributions
  .github/workflows/python-package.yml
  constraints-oldest.txt
  setup.cfg
Labels: CI

#342 Handle files not encoded with UTF-8
  CHANGES.rst
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
  src/darker/git.py
  src/darker/tests/conftest.py
  src/darker/tests/test_git.py
  src/darker/tests/test_utils.py
  src/darker/utils.py
Labels: bug

#349 Allow constraining linter versions in GitHub Action configuration
  CHANGES.rst
  README.rst
  action.yml
  action/main.py
  action/tests/test_main.py
Labels: enhancement, CI
