Repository akaihola/darker, pull requests merged in 2022-04, with the labels that each got.

#348 Add information about using Emacs with darker
  README.rst
Labels: documentation

#325 Updated README for issue#294
  README.rst
Labels: documentation

#300 Format docstrings as complete chunks
  CHANGES.rst
  src/darker/diff.py
  src/darker/git.py
  src/darker/multiline_strings.py
  src/darker/tests/test_diff.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main_blacken_single_file.py
  src/darker/tests/test_multiline_strings.py
Labels: bug, help wanted

#352 Rename `--jobs` to `-W` / `--workers`
  CHANGES.rst
  README.rst
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/concurrency.py
  src/darker/config.py
  src/darker/help.py
  src/darker/tests/test_command_line.py
Labels: enhancement, help wanted, review needed

#238 isort only if imports at the top of the module were edited
  CHANGES.rst
  src/darker/__main__.py
  src/darker/diff.py
  src/darker/git.py
  src/darker/import_sorting.py
  src/darker/tests/test_git.py
  src/darker/tests/test_import_sorting.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_blacken_single_file.py
Labels: enhancement

#353 Allow user to force syntax highlighting using config file, env var or command line. Enable syntax highlighting in GitHub Action.
  CHANGES.rst
  README.rst
  action.yml
  action/main.py
  action/tests/test_main.py
  constraints-oldest.txt
  setup.cfg
  src/darker/__main__.py
  src/darker/argparse_helpers.py
  src/darker/command_line.py
  src/darker/config.py
  src/darker/help.py
  src/darker/highlighting/__init__.py
  src/darker/highlighting/with_pygments.py
  src/darker/highlighting/without_pygments.py
  src/darker/linting.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_highlighting.py
  src/darker/tests/test_linting.py
  src/darker/tests/test_main.py
Labels: enhancement, help wanted, review needed

#357 Update `cachix/install-nix-action` to `v17`, downgrade to Python 3.9 on macOS Nix
  .github/workflows/python-package.yml
  CHANGES.rst
  default.nix
Labels: bug, CI

#356 Support the `NO_COLOR` environment variable
  CHANGES.rst
  constraints-oldest.txt
  setup.cfg
  src/darker/config.py
  src/darker/tests/test_highlighting.py
Labels: enhancement

#347 Contributors since 2022-03-27
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
  release_tools/update_contributors.py
Labels: documentation

#359 Use `-c PATH`/`--config PATH` for Darker config
  CHANGES.rst
  src/darker/command_line.py
  src/darker/config.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_config.py
Labels: enhancement

#360 Release 1.5.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  action.yml
  src/darker/version.py
Labels: release

#363 Fix `darker -r a..b .`
  CHANGES.rst
  src/darker/git.py
  src/darker/tests/test_main.py
Labels: bug

#365 Use CI to ensure README contains usage text
  .github/workflows/help-in-readme.yml
  CHANGES.rst
Labels: CI
