Repository akaihola/darker, pull requests merged in 2022-12, with the labels that each got.

#414 Fine-tune README section on PyCharm integration
  README.rst
Labels: documentation

#418 No development install in `help-in-readme.yml`
  .github/workflows/help-in-readme.yml
  CHANGES.rst
Labels: bug, CI

#421 Use `GITHUB_TOKEN` in the `test-bump-version` workflow
  .github/workflows/test-bump-version.yml
  CHANGES.rst
  release_tools/bump_version.py
Labels: CI

#420 Fixup RST spacing issue from PR #414
  README.rst
Labels: documentation

#417 Add new contributors until Dec'22
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
Labels: documentation

#419 Release version 1.6.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  action.yml
  src/darker/version.py
Labels: release

#423 Update CHANGES.rst for 1.6.0 release
  CHANGES.rst
Labels: documentation

#429 Pin Black to 22.12.0 in CI build
  .github/workflows/python-package.yml
  CHANGES.rst
Labels: CI

#415 Add support for Python 3.11
  .github/workflows/python-package.yml
  .github/workflows/test-future.yml
  CHANGES.rst
  default.nix
  setup.cfg
Labels: enhancement

#427 Omit `--initial-branch=master` on old Git versions
  CHANGES.rst
  src/darker/git.py
  src/darker/tests/conftest.py
Labels: bug, CI

#430 Guard against Black compatibliity breakage
  .github/workflows/test-future.yml
  README.rst
  action.yml
  action/main.py
  release_tools/bump_version.py
Labels: documentation, enhancement

#428 Document development environment setup
  CHANGES.rst
  CONTRIBUTING.rst
Labels: documentation

#435 Remove revision from GitHub Action example
  CHANGES.rst
  README.rst
Labels: documentation

#436 Fix `test-bump-version` workflow in a release branch
  CHANGES.rst
  release_tools/bump_version.py
Labels: bug, CI

#437 Bugfix to GitHub Action implementation
  action/main.py
Labels: bug, CI

#433 Instruct how to update contributors
  CHANGES.rst
  CONTRIBUTING.rst
  CONTRIBUTORS.rst
  README.rst
  release_tools/update_contributors.py
Labels: documentation

#402 Update vulnerable dependencies (Nov 2022)
  .github/workflows/test-future.yml
  setup.cfg
Labels: CI

#434 Document how to pin reformatters/linters in pre-commit configuration
  CHANGES.rst
  README.rst
  release_tools/bump_version.py
Labels: documentation

#438 Release version 1.6.1
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  action.yml
  src/darker/version.py
Labels: release
