Repository akaihola/darker, pull requests merged in 2023-01, with the labels that each got.

#441 Fix compatibility of test suite with Pygments 2.14.0
  CHANGES.rst
  src/darker/tests/test_highlighting.py
  src/darker/tests/test_main.py
Labels: bug, CI

#440 Make unit tests compatible with `pytest --log-cli-level=DEBUG`
  CHANGES.rst
  src/darker/tests/test_git.py
  src/darker/tests/test_linting.py
Labels: enhancement, CI

#439 Limit Black version on Windows builds, too
  .github/workflows/python-package.yml
  CHANGES.rst
Labels: bug, CI

#444 Fix Git error output
  CHANGES.rst
  src/darker/git.py
Labels: bug

#411 support target-version
  .github/workflows/python-package.yml
  CHANGES.rst
  README.rst
  pyproject.toml
  src/darker/__main__.py
  src/darker/black_diff.py
  src/darker/command_line.py
  src/darker/config.py
  src/darker/help.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_command_line.py
Labels: enhancement

#452 Code and documentation clean-ups (Jan 2023)
  .github/workflows/mypy.yml
  .gitignore
  src/darker/black_diff.py
  src/darker/tests/helpers.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_config.py
Labels: documentation, refactoring

#453 Add a work-around for cleaning up temporary directories. Needed for Python 3.7 on Windows.
  CHANGES.rst
  src/darker/tests/conftest.py
  src/darker/tests/test_linting.py
  src/darker/utils.py
Labels: bug, CI

#446 Link to GitHub searches on Darker in README
  CHANGES.rst
  README.rst
Labels: documentation

#455 Split/join command lines using `shlex` from Python stdlib
  .github/workflows/python-package.yml
  CHANGES.rst
  README.rst
  src/darker/git.py
  src/darker/linting.py
  src/darker/tests/test_linting.py
Labels: bug

#393 Run linters twice: 1) baseline, 2) current; then show new messages
  CHANGES.rst
  README.rst
  src/darker/__main__.py
  src/darker/black_diff.py
  src/darker/diff.py
  src/darker/git.py
  src/darker/linting.py
  src/darker/tests/conftest.py
  src/darker/tests/test_black_diff.py
  src/darker/tests/test_diff.py
  src/darker/tests/test_git.py
  src/darker/tests/test_linting.py
  src/darker/tests/test_main.py
Labels: bug, enhancement

#458 Use `!r` for quotes in format strings
  setup.py
  src/darker/__main__.py
  src/darker/tests/test_main.py
Labels: CI

#459 Add docstring linting to the Darker repo
  CHANGES.rst
  setup.cfg
  src/darker/diff.py
Labels: CI

#461 Configure `coverage` to use relative paths in the Darker repo
  .coveragerc
  CHANGES.rst
Labels: CI

#308 Add conversion to f-strings using `flynt`
  .github/workflows/help-in-readme.yml
  .github/workflows/mypy.yml
  CHANGES.rst
  README.rst
  constraints-oldest.txt
  mypy.ini
  setup.cfg
  src/darker/__main__.py
  src/darker/command_line.py
  src/darker/config.py
  src/darker/diff.py
  src/darker/fstring.py
  src/darker/git.py
  src/darker/help.py
  src/darker/import_sorting.py
  src/darker/linting.py
  src/darker/tests/helpers.py
  src/darker/tests/test_command_line.py
  src/darker/tests/test_fstring.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_blacken_and_flynt_single_file.py
  src/darker/tests/test_main_blacken_single_file.py
Labels: enhancement

#432 Explain configuration of reformatter/linter tools in README and in `--help`
  CHANGES.rst
  README.rst
  src/darker/help.py
Labels: documentation
