Repository akaihola/darker, pull requests merged in 2023-05, with the labels that each got.

#486 Fix local action outside of this repo
  CHANGES.rst
  action.yml
Labels: bug, CI

#479 Add contributors since 2023-03-25
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
Labels: documentation

#491 Add a `News` link on the PyPI page
  setup.cfg
Labels: documentation

#496 Fix Python 3.12 compatibility in multi-line string scanning
  CHANGES.rst
  src/darker/git.py
  src/darker/multiline_strings.py
  src/darker/tests/test_multiline_strings.py
Labels: bug

#499 Avoid Mypy error when there's an `__init__.py` in the repo root
  CHANGES.rst
  constraints-oldest.txt
  setup.cfg
  src/darker/linting.py
  src/darker/tests/test_linting.py
Labels: bug
