Repository akaihola/darker, pull requests merged in 2024-02, with the labels that each got.

#530 Update to `actions/setup-python@v5`
  .github/workflows/isort.yml
  .github/workflows/mypy.yml
  .github/workflows/pylint.yml
  .github/workflows/python-package.yml
  .github/workflows/pyupgrade.yml
  .github/workflows/safety.yml
  .github/workflows/test-bump-version.yml
  .github/workflows/test-future.yml
  README.rst
Labels: CI

#531 Fix miscellaneous test failures
  .github/workflows/python-package.yml
  default.nix
  pytest.ini
  src/darker/concurrency.py
  src/darker/tests/helpers.py
Labels: CI

#534 Limit Black below version 24.2 until incompatibility is resolved
  .github/workflows/python-package.yml
  CHANGES.rst
  setup.cfg
Labels: enhancement

#536 Run Pytest in installed package in Nix test
  .github/workflows/python-package.yml
Labels: bug, CI

#537 Drop Python 3.7 tests
  .github/workflows/python-package.yml
  CHANGES.rst
Labels: CI

#514 Add contributors since June 2023
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
  release_tools/update_contributors.py
Labels: documentation

#519 Fix args list for pre-commit hook
  CHANGES.rst
  README.rst
Labels: bug, documentation

#520 Fix typo in pylint example, unmatched " Update README.rst
  README.rst
Labels: bug, documentation

#515 Bugfix black .gitignore usage
  setup.cfg
  src/darker/black_diff.py
  src/darker/tests/test_black_diff.py
Labels: bug

#539 Ignore unused arguments in `gen_python_files` test
  src/darker/tests/test_black_diff.py
Labels: CI

#538 Release 1.7.3
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  action.yml
  src/darker/version.py
Labels: release

#540 Drop support for EOL Python 3.7
  .github/workflows/pyupgrade.yml
  action/tests/test_main.py
  release_tools/bump_version.py
  release_tools/update_contributors.py
  setup.cfg
  src/darker/black_diff.py
  src/darker/config.py
  src/darker/git.py
  src/darker/import_sorting.py
  src/darker/linting.py
  src/darker/tests/conftest.py
  src/darker/utils.py
Labels: enhancement
