Repository akaihola/darker, pull requests merged in 2024-08, with the labels that each got.

#545 Filter out unmodified files from list of changed files
  CHANGES.rst
  src/darker/git.py
  src/darker/tests/test_git.py
  src/darker/tests/test_main_revision.py
Labels: enhancement

#609 Add GitHub Action to summarize recent activity in a discussion
  .github/workflows/recent-activity-summary.yml
  CHANGES.rst
Labels: CI

#611 Ignore environment in Git tests
  src/darker/tests/test_git.py
Labels: bug, CI

#613 refactor,test: huge test_main.py into pieces
  pyproject.toml
  src/darker/tests/examples.py
  src/darker/tests/test_main.py
  src/darker/tests/test_main_format_edited_parts.py
  src/darker/tests/test_main_isort.py
Labels: CI

#614 Update to Darkgraylib 2.0.1 (fixes Git "dubious ownership" error)
  CHANGES.rst
  constraints-oldest.txt
  setup.cfg
Labels: bug

#734 fix: avoid flake8-bugbear version with broken deps
  .github/workflows/flake8.yml
Labels: bug, CI

#589 Add Black `--preview` support
  CHANGES.rst
  README.rst
  src/darker/__main__.py
  src/darker/black_diff.py
  src/darker/command_line.py
  src/darker/help.py
  src/darker/tests/test_command_line.py
Labels: enhancement
