Repository akaihola/darker, pull requests merged in 2025-02, with the labels that each got.

#812 Use newest v4 upload/download artifacts action
  .github/workflows/python-package.yml
  .github/workflows/test-working-directory.yml
  CHANGES.rst
Labels: CI

#815 Fix python 3.12 deprecation warning
  CHANGES.rst
  src/darker/__main__.py
Labels: bug

#760 Only log flynt result if --flynt enabled
  CHANGES.rst
  src/darker/__main__.py
Labels: bug

#810 uv work: implement oldest dependencies into pyproject.toml
  .github/workflows/python-package.yml
  .github/workflows/test-future.yml
  .gitignore
  .pre-commit-config.yaml
  constraints-future.txt
  constraints-oldest.txt
  pyproject.toml
  setup.cfg
Labels: enhancement, CI
